---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: lumenconcept-user1-v1-svc
  name: lumenconcept-user1-v1-svc
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      run: lumenconcept-user1-v1-svc
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: lumenconcept-user1-v1-svc
    spec:
      containers:
      - name: lumenconcept-user1-v1-svc
        image: docker.io/zonumserdnaua/lumenconcept-user1-v1
        imagePullPolicy: IfNotPresent
        env:
          - name: VOX_COUCHDB_URL
            value: "http://admin:admin@192.168.50.4:5984"
        ports:
        - containerPort: 3001
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: lumenconcept-user1-v1-svc
  name: lumenconcept-user1-v1-svc
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3001
  selector:
    run: lumenconcept-user1-v1-svc
  sessionAffinity: None
  type: LoadBalancer